### ISSUE TITLE
Can install Pi-Kiss with pi OS 64bit?

### ISSUE THREAD

**Issue by gamerthundertv** [jmcerrejon/PiKISS#101]
I use Raspberry pi OS 64bit and i don't Pi-Kiss can install and play game?

**Comment by jmcerrejon** [comment]
TL;DR: Nope

Please read the [DOC](https://github.com/jmcerrejon/PiKISS#-introducing-pikiss-).

**Comment by gamerthundertv** [comment]
So in the future will you update Pi-Kiss running with Pi OS 64bit?

**Comment by jmcerrejon** [comment]
Yes, but not all the app/games.

**Comment by gamerthundertv** [comment]
thanks
