### ISSUE TITLE
GTAIII and GTAVC

### ISSUE THREAD

**Issue by tso4ev** [jmcerrejon/PiKISS#102]
On RPI4B after installing and using original games files from my linux steam account games start but after the first scene stuck and don't respond anymore (aka at the moment I need to start playing just freeze)

**Comment by jmcerrejon** [comment]
Check the next: 

- RPi OS 32 bits.
- Games data files from Steam installed at /home/pi/games/GTAVC or GTAIII.
- You don't have directory /home/pi/Games like with Twister OS.

**Comment by tso4ev** [comment]
Im running 32 bit raspbian and game files are in home/pi/games/GTAVC and GTAIII right place everything is on spot they both start and then freeze after the introduction scenes

**Comment by jmcerrejon** [comment]
I don't know how to fix that 🤷‍♂️. Sorry. First time I hear that issue and I don't know how to replicate it on my RPi. You can join to Pi Lab Discord server and ask other users about it.

**Comment by tso4ev** [comment]
No worries I will find what's  the problem 
running it with the terminal shows that alsa buffer soze is overrun 
have problems with other games too (missing sound) but they run 
sudo apt update && sudo apt upgrade
sudo rpi-upgrade 
doesnt fix it .. neofetch shows that Im on 32 bin raspbian will try to reinstal the alsa later on
