### ISSUE TITLE
I can't install Serious Sam game like your video

### ISSUE THREAD

**Issue by gamerthundertv** [jmcerrejon/PiKISS#103]
When I choose to download Serious Sam game there is no list game like video https://www.youtube.com/watch?v=yhpyPaeeHMA&list=PLXhElW3ALmWh8p0mn1ZECawkKyF8QzNNP&index=23&ab_channel=JoseCerrejonJoseCerrejon
which only installs the required libraries?

**Comment by jmcerrejon** [comment]
Do you have the game data files configured at magic-air-copy-pikiss.txt?. It's necessary to achieve install that. Please check the README.md file in the repository.
