### ISSUE TITLE
Nothing Downloads 

### ISSUE THREAD

**Issue by FlyingJesy** [jmcerrejon/PiKISS#106]
![IMG_20210625_221420](https://user-images.githubusercontent.com/86497756/123486859-c5b32f80-d604-11eb-8426-e78048b090f0.jpg)

After I downloaded PIKISS and tried to install anything it would say it installed the application (mGBA in this case), but would fail to launch ot run any of the games I installed. It would pop up the message shown on the image above and wouldn't load or even open the game when I tried to launch it from the menu. If anyone can help me with this I'll be grateful.

**Comment by jmcerrejon** [comment]
Fixed https://github.com/jmcerrejon/PiKISS/commit/dfbfe590b63180f80bb385d05d1718ff1ac66b31
