### ISSUE TITLE
Webcam doesn't work in Zoom

### ISSUE THREAD

**Issue by mngr** [jmcerrejon/PiKISS#107]
I've installed PiKiss, then Zoom. It starts up, but the video from my WaveShare RPi Camera (G) is not shown (gray screen), though there is no any error and Zoom show something called bcm2835-isp as the camera device. When I run Zoom as a web app in the browser it works correctly.

**Comment by jmcerrejon** [comment]
Honestly, I only did an installer, so better if you search on forums or official website support.

The only thing I can say is that it's working with the official RPi webcam.

Good luck!
