### ISSUE TITLE
Error when installing on Raspberry Pi 4

### ISSUE THREAD

**Issue by lesp** [jmcerrejon/PiKISS#11]
Hello, great project!
I tried to install using the advised method on my Raspberry Pi 4 4GB model. However I received this error message
`"Sorry. PiKISS is only for Raspberry Pi boards."`
I used curl to download the installer and edited line 17
From
`if [[ ! $(cat /proc/cpuinfo | grep 'BCM2708\|BCM2709\|BCM2835') ]]; then`
To
`if [[ ! $(cat /proc/cpuinfo | grep 'BCM2708\|BCM2709\|BCM2835\|BCM2711') ]]; then`
And I believe that this solved the issue. Apologies for not doing this via a pull / fork. I know enough about GitHub to do the basics, but never done anything more advanced.

I hope this helps.
Best
Les Pounder @biglesp on Twitter.

**Comment by jmcerrejon** [comment]
Just a user send me the same comment yesterday. Fixed!. Thanks man!.
