### ISSUE TITLE
Dead link in README.md

### ISSUE THREAD

**Issue by FlrQue** [jmcerrejon/PiKISS#110]
I believe that I've found a dead-link in the second part of README's section "Introducing PiKISS".
TwisterOS link points to the https://raspbian-x.com/ website which appears to be dead.

**Comment by jmcerrejon** [comment]
Yeah it's possible. Thanks for catch the bug 😅

**Comment by jmcerrejon** [comment]
Fixed https://github.com/jmcerrejon/PiKISS/commit/7ab0dfd438f8664d06f187bdf3c70aef4c9e33b8
