### ISSUE TITLE
Suggestion:The sims 1

### ISSUE THREAD

**Issue by jackygoule** [jmcerrejon/PiKISS#113]
Hello, very nice job with pi kiss.
The sims 1 will be very cool to run on the pi4 and the install file can find on abandonware site.
I already test with wine but the game never run .
Wine :bad format for .exe
Otherwise i found a way to have french language in half life but i don't know where i can write my job.
Thanks for your jobs.

**Comment by jmcerrejon** [comment]
I'm afraid I never going to support wine games because the possibilities are endless and difficult to give support for each wine game. I prefer to focus on open-source games, but thanks for the suggestion.
