### ISSUE TITLE
box86 install problem

### ISSUE THREAD

**Issue by actraiser30** [jmcerrejon/PiKISS#117]
Hello i have a Raspberry pi4 with latest raspbian buster desktop

im trying to compile box86 from source to get the latest version and its not possible i always get a message saying: 

already up to date

your box is already updated skipping

i have not installed box86 in anyway eg: from binary how is up to date ?

must be a bug can you check it please

thanks

**Comment by jmcerrejon** [comment]
Yes, you have. Check If you have the directory _/home/pi/box86_. 😉

**Comment by actraiser30** [comment]
that command  returns nothing
and as i said i have not install it

**Comment by jmcerrejon** [comment]
That command is used for check if it's installed. If return the path, then you have install it and show that message. Very simple, so I can't do anything more, apologies.

**Comment by actraiser30** [comment]
you are weird anyway thanks

**Comment by jmcerrejon** [comment]
I've tested on my Pi and you are right, @actraiser30.

The point is that line should be working...Mm, I need to test it deeply.

My apologies, but I will not allow insults and I have deleted your previous message offending me. I will try to fix it when I have 
 enough time.

**Comment by actraiser30** [comment]
Ok thank you and sorry

Στις Σάβ, 25 Σεπ 2021, 19:27 ο χρήστης Jose Cerrejon <
***@***.***> έγραψε:

**Comment by actraiser30** [comment]
If its possible to update also the pre- compiled version its almost a year
old
Thanks

Στις Σάβ, 25 Σεπ 2021, 19:30 ο χρήστης G D ***@***.***> έγραψε:

**Comment by jmcerrejon** [comment]
Fixed b27001663c5d3fcf986a859d119a4742cb53d9a9
