### ISSUE TITLE
Download Path for Diablo 1 outdated

### ISSUE THREAD

**Issue by lLixlL** [jmcerrejon/PiKISS#123]
Hey there,

thank you for your work!

I just saw that there is a new Diablo 1 Release (1.3.0): https://github.com/diasurgical/devilutionX/releases/tag/1.3.0
Could you please update the path in the script?
https://github.com/diasurgical/devilutionX/releases/download/1.3.0/devilutionx-linux-armhf.zip

Cheers
Felix

**Comment by jmcerrejon** [comment]
hey!. Thank YOU. I'll take a look. 🥰

**Comment by jmcerrejon** [comment]
Fixed 5425b7b8bd57497327d91d45467b9894385fbb3d
