### ISSUE TITLE
The noop I/O scheduler is no longer available

### ISSUE THREAD

**Issue by norambna** [jmcerrejon/PiKISS#124]
I wanted to try the **noop** scheduler, so I tried the [Tweaks -> Others script](https://github.com/jmcerrejon/PiKISS/blob/master/scripts/tweaks/others.sh). But cat /sys/block/mmcblk0/queue/scheduler still gives me: [mq-deadline] kyber none

It seems **noop** was removed from the linux kernel since 5.0!
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=f382fb0bcef4c37dc049e9f6963e3baf204d815c

**Comment by jmcerrejon** [comment]
No way!... thanks for the advice 😉

**Comment by jmcerrejon** [comment]
Removed 5425b7b8bd57497327d91d45467b9894385fbb3d
