### ISSUE TITLE
Quake installation issue

### ISSUE THREAD

**Issue by Trotter73** [jmcerrejon/PiKISS#125]
Hi, 

Found a couple of issues with quake.sh

The URL here has changed,

readonly Q2_HIGH_TEXTURE_PAK_URL="https://deponie.yamagi.org/quake2/texturepack/q2_textures.zip"
is now
readonly Q2_HIGH_TEXTURE_PAK_URL="https://deponie.yamagi.org/quake2/texturepack/textures.zip"

This line has a unneeded "readonly" at the end breaking things...

readonly Q2_HIGH_TEXTURE_MODELS_URL="https://deponie.yamagi.org/quake2/texturepack/models.zip"**readonly**

**Comment by jmcerrejon** [comment]
Fixed 29261b5ccbef4a036c68656d48574ebfa7af6e0d
