### ISSUE TITLE
Compile options 

### ISSUE THREAD

**Issue by Trotter73** [jmcerrejon/PiKISS#126]
Hi,

A question more than a bug report, hope you don't mind....

When compiling for the Pi4 you use -mtune=cortex-a53, as the pi 4 is an a72 capable processor is there an important reason you have not used mtune=cortex-a72 ?

I have been compiling stuff myself using 72 and and wondering if sould have :)

**Comment by jmcerrejon** [comment]
You are right. Honestly I use to type the command manually. Don't remember I have that parameter on any function 😅

I'll fix that ASAP. Thanks!

**Comment by jmcerrejon** [comment]
Improved 19bde65b383fd187e34967c4d003da7ef171ced7
