### ISSUE TITLE
DOSBox-X MS-DOS Emulator does not start.

### ISSUE THREAD

**Issue by Rak1ta** [jmcerrejon/PiKISS#128]
The program does not run on a clean installation RaspiOS (Debian 11 "Bullseye")
`Press [ENTER] to run...
./dosbox-x: error while loading shared libraries: libfluidsynth.so.1: cannot open shared object file: No such file or directory`

**Comment by jmcerrejon** [comment]
Fixed 19bde65b383fd187e34967c4d003da7ef171ced7
