### ISSUE TITLE
Trying on ubuntu mate 20.10, pi directory issue

### ISSUE THREAD

**Issue by NigamAnu1975** [jmcerrejon/PiKISS#132]
Hi 
I am trying it on ubuntu mqte 20.10. When running box86 it says could not find pi directory. My directory is named aimachine so where are these paths set. Kindly help
Thanks
Anurqg

**Comment by jmcerrejon** [comment]
Thanks for the feedback, but PiKISS only works on Raspberry Pi OS 32 bits
