### ISSUE TITLE
insecureHash

### ISSUE THREAD

**Issue by Abelkrijgtalles** [jmcerrejon/PiKISS#134]
hashlib.sha1 is insecure. Consider changing it to a secure hashing algorithm (e.g. SHA256).
res/groove.py Line 46:
`return rnd + `**hashlib.sha1**`('%s:%s:%s:%s' % (method, _token, secret, rnd)).hexdigest()`

**Comment by jmcerrejon** [comment]
Please, use the same issue opened few minutes ago. Thanks.
