### ISSUE TITLE
Errors when installing RetroArch

### ISSUE THREAD

**Issue by norambna** [jmcerrejon/PiKISS#137]
Hi! I just did a fresh install of Raspberry Pi OS Bullseye. Then I installed PiKISS -> Emulation -> RetroArch and got errors when the script was installing the cores:

> Installing cores...
> 
> Downloading...
> 
> libretro_cores.tar.gz                     100%[=====================================================================================>] 126.86M  2.58MB/s    in 62s     
> 
> Extracting...
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
> 
> Cores installed:
> 
> ls: cannot access '*.so': No such file or directory

So I don't have any 'Cores' right now and I also have no RetroArch Icon in my Applications Menu -> Games

This is my first time trying PiKISS on Bullseye. The RetroArch script was running fine on Buster.

Thanks in advance!

**Comment by foxhound311** [comment]
Think it’s an issue with tar files created on macOS, it’ll get looked into soon. In the meantime you can grab the cores from here 

https://archive.org/details/RetroArch-rpi4

**Comment by jmcerrejon** [comment]
You are right, @foxhound311. **Fixed!**. The only issue is that you need a restart to get the icon in the menu. I don't know why. 😅

**Comment by elguaxo** [comment]
No errors when extracting now! And the icon was there after a restart. Thanks!

But the previous libretro_cores.tar.gz had 80 cores and the current one has only 51. I noticed it since pcsx_rearmed_libretro.so is missing and I use that one a lot. I downloaded the cores now from the link provided Foxhound311! Thanks.

**Comment by jmcerrejon** [comment]
> No errors when extracting now! And the icon was there after a restart. Thanks!
> 
> But the previous libretro_cores.tar.gz had 80 cores and the current one has only 51. I noticed it since pcsx_rearmed_libretro.so is missing and I use that one a lot. I downloaded the cores now from the link provided by @foxhound311! Thanks.

Ok, I'll update all the cores. Good catch @elguaxo !

**Comment by MopheusDG** [comment]
Hi, I've just installed PiKiss and I'm having the same problem with the Cores. Proposed solution worked but it seems the installation process has not been fixed. Not sure if you are aware.

Thanks.

**Comment by foxhound311** [comment]
> Hi, I've just installed PiKiss and I'm having the same problem with the Cores. Proposed solution worked but it seems the installation process has not been fixed. Not sure if you are aware.
> 
> Thanks.

@jmcerrejon you and your mac 😂🤦🏻‍♂️

**Comment by jmcerrejon** [comment]
Easy @foxhound311! 😂

The compressed file is OK, I had a typo with a variable name.

Fixed (https://github.com/jmcerrejon/PiKISS/commit/bb5edb9a2a103a2d4d0baf09f857cfd33016a8fa)

Thanks, @MopheusDG!🍻
