### ISSUE TITLE
App Request : Add box64 (64bit only)

### ISSUE THREAD

**Issue by Jai-JAP** [jmcerrejon/PiKISS#142]
Add [box64](https://github.com/ptitSeb/box64)
App similar to Box86 but for x86_64 on arm64

Also Zoom on Box64 is much newer and stable. So if possible also add Zoom for 64 bit using box64

**Comment by Jai-JAP** [comment]
Any updates?

**Comment by jmcerrejon** [comment]
Sorry the delay... update your PiKISS and enjoy 😜

cd240f9c6b628ba0a6bb047090310c7f0335e913
