### ISSUE TITLE
Scrcpy failure to launch? 

### ISSUE THREAD

**Issue by Phelnacra** [jmcerrejon/PiKISS#143]
Have a fresh install of Pi OS and a Samsung Galaxy S21+ ULTRA. 
I followed all instructions from this video linked below to get scrcpy working to mirror my Android via USB. However, I get this error and the terminal closes itself. 

https://imgur.com/a/8lUOMgP

https://youtu.be/ciMx7hWYJE4

Any help appreciated. I am new to Pi related projects and could really use this one for my prokect car :-/

**Comment by jmcerrejon** [comment]
I just upgrade the script and give support for 64 bits. 2e58ab722a022a9391fa432db767cd8528eebce5

Tested and working. Try with the ./rpiplay.sh command from Terminal or the Icon inside the Desktop menu.

_PiKISS_ only install the app, so to fix any issue, you must go to the original repository at https://github.com/FD-/RPiPlay

Good luck! 🥰
