### ISSUE TITLE
Not working with Rasperry Pi OS 64 bit beta

### ISSUE THREAD

**Issue by DerDiplomatPi** [jmcerrejon/PiKISS#15]
Hi, thank you for your work on piKiss! I'm using the Raspberry Pi OS 64bit beta. After installing piKiss I get this error after klicking: "Kindprozess »xterm« konnte nicht ausgeführt werden (Datei oder Verzeichnis nicht gefunden)" [German error code], translated: Child process "xterm" could not be executed (file or directory not found).
Starting in terminal the following error is showed:
pi@raspberrypi:~/piKiss $ sh piKiss.sh
piKiss.sh: 470: ./scripts/helper.sh: Syntax error: "(" unexpected

What can I do or is this all about 64bit support?

Best Regards,
DerDiplomatPi

**Comment by jmcerrejon** [comment]
Sorry. PiKISS only support Raspberry Pi OS 32 bits. 64 bits is in a early stage yet 😉


Jose Cerrejon
Freelance

📖  ⠀Blog: misapuntesde.com
🎥  ⠀Youtube: youtube.com/c/josecerrejonpi
👾  ⠀Discord: discord.gg/Y7WFeC5FeC5
💰 ⠀Patreon: patreon.com/cerrejon
👨🏻‍💻 ⠀LinkedIn: es.linkedin.com/in/jmcerrejon/
🐙 ⠀GitHub: github.com/jmcerrejon
🐦 ⠀Twitter: @ulysess10
