### ISSUE TITLE
Cannot install PiKiss

### ISSUE THREAD

**Issue by jonathanpmartins** [jmcerrejon/PiKISS#151]
The installation URL is broken: https://git.io/JfAPE

```
curl -sSL https://git.io/JfAPE | bash
```
```
curl: (60) SSL: no alternative certificate subject name matches target host name 'git.io'
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

If I visit the page, it gives me a 404 return

**Comment by jmcerrejon** [comment]
Working on my side: Raspberry Pi OS 64 bits updated right now on a Pi 4 4 Gb through ethernet.

So I guess the issue is on your side

![2022-05-19-223649_1440x900_scrot](https://user-images.githubusercontent.com/1942431/169400387-5ec08727-b5e5-4e89-afaf-4eefb46e530a.png)
