### ISSUE TITLE
QUAKE 1 is not downloading

### ISSUE THREAD

**Issue by Rak1ta** [jmcerrejon/PiKISS#154]
```
Press [Enter] to install the game...
Installing Quake, please wait...
Installing binary files...
Downloading...
quakespasm-0.94.3-r 100%[===================>] 764,89K  3,29MB/s    за 0,2s    
Extracting...
Generating icon...
Downloading...
quake106.zip        100%[===================>]   8,67M  5,10MB/s    за 1,7s    
Extracting...
Done!. You can play typing /home/pi/games/quake/run.sh or opening the Menu > Games > Quake.


File does not exist.
· Something is wrong.
· Try to install again.

Press [Enter] to go back to the menu...

```
I tried an early [version](https://github.com/jmcerrejon/PiKISS/blob/3c876d1aacc4ae91353cb21b91a64daff9299e70/scripts/games/quake.sh) of the script - it works.

i use: RaspiOS 32bit Debian10 Buster/11 Bullseye

**Comment by Rak1ta** [comment]
`./quakespasm: ./quakespasm: unable to run binary file`

**Comment by jmcerrejon** [comment]
It works on latest Bullseye 32-bit. I have to fix the shareware game data version.

![2022-07-21-235404_1280x720_scrot](https://user-images.githubusercontent.com/1942431/180321817-53b2c553-d880-4b2d-84d8-fb0aeaa9a5e6.png)

**Comment by Rak1ta** [comment]
@jmcerrejon it works for me
