### ISSUE TITLE
DOSBox-X won't start

### ISSUE THREAD

**Issue by Rak1ta** [jmcerrejon/PiKISS#155]
Program not working after [update](https://github.com/jmcerrejon/PiKISS/commit/19bde65b383fd187e34967c4d003da7ef171ced7).
This [version](https://github.com/jmcerrejon/PiKISS/blob/84d2aef1349e8764d4d8fa6ba74517515f80c696/scripts/emus/msdos.sh) worked earlier, but it is not on the server.

Requires at startup:
```
Press [ENTER] to run...
./dosbox-x: error while loading shared libraries: libslirp.so.0: cannot open shared object file: No such file or directory
```
Such a package is missing from Buster
https://packages.debian.org/bullseye/libslirp-dev

I have a copy of DOSBox-X 0.83.11: [dosbox.zip](https://github.com/jmcerrejon/PiKISS/files/8971030/dosbox.zip)

i use: RaspiOS 32bit Debian10

**Comment by jmcerrejon** [comment]
Fixed with a95884cddca3030935bfcef46eace7d0ca09d2bc

I'm not giving support to Debian 10, sorry.

**Comment by Rak1ta** [comment]
@jmcerrejon I know you only have Bullseye :(

**Comment by Rak1ta** [comment]
@jmcerrejon  libfluidsynth2 - can be added to dependencies, requires `libfluidsynth.so.2`
