### ISSUE TITLE
Improved compatibility with Buster.

### ISSUE THREAD

**Issue by Rak1ta** [jmcerrejon/PiKISS#157]
Can you keep old versions of packages from your site so that you can install applications with the old script if the new version does not work? Or add a warning when uninstalling the program that it will be impossible to install back on Buster, since there is no more support (this is the case when you changed something and made a new release)?

On the example of pi-apps, there are still a large number of Buster users. And the installation scripts there offer different software versions for each system. Thanks!

**Comment by jmcerrejon** [comment]
of course. I don't know if I can recover the other Buster-compatible files. Apologies for that.
