### ISSUE TITLE
Duckstation invalid archive

### ISSUE THREAD

**Issue by Rak1ta** [jmcerrejon/PiKISS#159]
`readonly BIOS_URL="https://dl.hexrom.com/rom/psx-bios-SCPH1001-hexrom_com.zip"`

This is the PCSX2 installer: 
![Безымянный](https://user-images.githubusercontent.com/88277343/176426624-5f7c2d36-bcf2-4db9-b18c-698664a70c66.png)

**Comment by symbios24** [comment]
Hello there can you update the Duckstation binary to the latest version please?
Thank you

**Comment by symbios24** [comment]
There isn't a 32bit latest version of duckstation?

Im not using 64bit os and not planning to use,as its not behaving/working correct and has many incompatibilities,if you want you can rollback to the previous 32bit version of duckstation
Thank you

**Comment by jmcerrejon** [comment]
I'm not planning to compile the latest version for Buster/Bullseye 32 bits. The current for 32 bits is the old one I already compiled... I'll ask to my patrons and they will decide on its retro compatibility.

**Comment by symbios24** [comment]
I mean to put back the previous version you already had before i did ask to compile any other

**Comment by jmcerrejon** [comment]
It's the same older version. I only compiled the 64 bits available at Gihub 🤷‍♂️

**Comment by jmcerrejon** [comment]
Fix Buster shortcut. 

fb8b6c80edff55b451ef2782423b04a0e6fb61b7

I close the issue finally. I'll think about upgrading/compiling for 32 bits. Thanks.
