### ISSUE TITLE
Raspberry Pi4 64 bit cannot show the desktop after installing vulkan

### ISSUE THREAD

**Issue by Johnqxy** [jmcerrejon/PiKISS#166]
It looks fine after installing vulkan, but if I reboot, I got "Cannot Currently Show the Desktop" from VNC, SSH connection is fine.
I reflashed my system twice and think it's about the vulkan driver

**Comment by jmcerrejon** [comment]
We have a thread open [here](https://github.com/jmcerrejon/PiKISS/issues/165). Join us!
