### ISSUE TITLE
SeriousSamClaasic with Mods for Raspberry  Pi 3B/3B+/4B/400

### ISSUE THREAD

**Issue by tx00100xt** [jmcerrejon/PiKISS#183]
I think Serious Sam needs no introduction. I want to tell you about the additions to this game.

Serious Sam Early Build is the period where Serious Sam was supposed to be a much bigger game than it turned out to be. Back then, it was known as Serious Sam Alpha. Generally, this period is between the development of In the Flesh (1996) and Test 1 (2000). The game was supposed to have much more levels, more enemies, and more weapons. 

The "early build" with the colored HUD was the first build called "Serious Sam", and it was supposed to be a full game. It was supposed to be something like Doom and Duke Nukem. The "early build" of the game was made in early 1998.

Thanks to the fans, an early build appeared as an add-on to the game Serious Sam The First Encounter called Serious Sam Alpha Remake.

The add-on contains 30 game levels. Sequential gameplay includes completing the levels of Egypt, Water Planet, Lava Planet, Green Planet, Ice Planet, Tropic Planet, Rock Planet and finishing the mission on the Space Crusader.

![Lava Planet](https://raw.githubusercontent.com/tx00100xt/SeriousSamAlphaRemake/main/Images/alpharemake_1.png)

![Ice Planet](https://raw.githubusercontent.com/tx00100xt/SeriousSamAlphaRemake/main/Images/alpharemake_2.png)

![Ice Planet End](https://raw.githubusercontent.com/tx00100xt/SeriousSamAlphaRemake/main/Images/alpharemake_3.png)

You can read more about creating a modification here:
https://github.com/tx00100xt/SeriousSamAlphaRemake/wiki

Another modification is XPLUS. XPLUS is a global modification that changes effects, models, weapons, textures to high definition. XPLUS was created by fans of the game Serious Sam and is distributed for free.

![XPLUS Oasis](https://raw.githubusercontent.com/tx00100xt/SeriousSamClassic/main/Images/samxplus_1.png)

![XPLUS Dunes](https://raw.githubusercontent.com/tx00100xt/SeriousSamClassic/main/Images/samxplus_2.png)

![XPLUS Sacred Yards](https://raw.githubusercontent.com/tx00100xt/SeriousSamClassic/main/Images/samxplus_3.png)

You can read more about her modifications here:
[About of XPLUS modification.](https://github.com/tx00100xt/SeriousSamClassic/wiki/About-XPLUS.md)

You can download ready-to-install deb packages for Raspberry Pi OS here: [Serious Sam Packages](https://github.com/tx00100xt/serioussam-packages)

For a portable installation, you can take the archives from here:
https://github.com/tx00100xt/SeriousSamClassic/releases/tag/v1.10.4
https://github.com/tx00100xt/SeriousSamClassic-VK/releases/tag/v1.10.4

Instructions for self-building can be found on Wiki:
[SeriousSamClassic Wiki](https://github.com/tx00100xt/SeriousSamClassic/wiki)
[SeriousSamClassic-VK Wiki](https://github.com/tx00100xt/SeriousSamClassic-VK/wiki)

**Comment by jmcerrejon** [comment]
I'm a very big Uncle Sam fan, so I'm gonna review the version I have on PiKISS & I'll include both mods If possible. Thank you so much for the info and take PiKISS into consideration.
