### ISSUE TITLE
Half Life - missing shared object

### ISSUE THREAD

**Issue by vliapis** [jmcerrejon/PiKISS#184]
After I setup HL through PIKISS and copy the VALVE directory from an installation I did on Win11 (GoG installation, not STEAM) to raspberry's half life directory, i get this error.

./xash3d: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory
I'm sure that more objects will be missings if I managed to fix the first error.
Why is this happening?
Using arm64bit Bulleye Debian.

**Comment by jmcerrejon** [comment]
See https://github.com/jmcerrejon/PiKISS/issues/59
