### ISSUE TITLE
The RetroArch script does not load all files.

### ISSUE THREAD

**Issue by Rak1ta** [jmcerrejon/PiKISS#186]
The site from which you receive files has shader (GLSL) archives. But the script doesn't load them. Please include these files in the emulator installation script.

https://buildbot.libretro.com/assets/frontend/

RetroPie uses this option, all in one folder.
`C:\Users\USER\Downloads\retropie-buster-4.8-rpi4_400.img\1.img\opt\retropie\configs\all\retroarch\`
[shaders.zip](https://github.com/jmcerrejon/PiKISS/files/11469703/shaders.zip) - taken from the last v.4.8 disk image

**Comment by jmcerrejon** [comment]
I see 3 files for shaders. What should I use? all of them? 🧐

**Comment by Rak1ta** [comment]
@jmcerrejon RetroPie uses [glsl shaders](https://github.com/RetroPie/common-shaders). But I haven't tried using libertro shaders. This would be incorrect, as I am using Debian Buster (armhf) for now.
I suggest you try to use **shaders_glsl.zip**

**Comment by jmcerrejon** [comment]
Added at 9c650184b76e6458438a37f634e1779da68e8681!

Sorry for the delay. Please test and tell me If the path is correct.
