### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by AngeloCorr99** [jmcerrejon/PiKISS#187]
Attempting to run any game from the terminal results in a segmentation fault. For example:

./scripts/games/eduke32.sh: line 25: 6180 segmentation fault 

Attempting to run it in any other way results in nothing. 
(Running on a Pi 3 B+ with a fresh install of Raspberry Pi OS)

**Comment by jmcerrejon** [comment]
32 or 64 bits?

**Comment by jmcerrejon** [comment]
After some research, It's an issue with resolutions. I tried 1280x720 and It works. All others I tried, showed segmentation fault. I compiled the engine again, always with the same result, so It's some kind of issue with RPi. Try 1280x720 OpenGL and tell me If It's working on your side. I let the issue open until your answer a few days more.

**Comment by AngeloCorr99** [comment]
> After some research, It's an issue with resolutions. I tried 1280x720 and It works. All others I tried, showed segmentation fault. I compiled the engine again, always with the same result, so It's some kind of issue with RPi. Try 1280x720 OpenGL and tell me If It's working on your side. I let the issue open until your answer a few days more.

I tried changing the resolution under preferences and then screen configuration, and it didn't work. Is there another way I can change the resolution? Or is there something I have to do when I launch the game?

**Comment by jmcerrejon** [comment]
It depends on the engine, so there is nothing I can do. I change the resolution in the first window (try software rendered instead, too). I think is a problem detecting the monitor.
Another possibility is to use another engine (not eduke32), but I need to compile it. Try the game Blood. The engine support Duke Nukem, and I could use it in my script replacing the first one. 
I'll dive into that.
