### ISSUE TITLE
Not installing on Bookworm 64-bit today

### ISSUE THREAD

**Issue by Botspot** [jmcerrejon/PiKISS#199]
Today we have been receiving multiple error reports for pikiss installation failures.
One such example is included below.
[install-fail-piKiss.txt](https://github.com/jmcerrejon/PiKISS/files/13402102/install-fail-piKiss.txt)
Your install script seems to be exiting with a nonzero exit code, without any further explanation. Please investigate and fix.

**Comment by jmcerrejon** [comment]
Thanks for the feedback!

Fixed https://github.com/jmcerrejon/PiKISS/commit/54e29fd8d1b353c64ac2ba8074544066f026dac1

![Screenshot 2023-11-19 at 10 10 47](https://github.com/jmcerrejon/PiKISS/assets/1942431/7fb1bea9-8a87-442b-a058-fd6627f80532)
