### ISSUE TITLE
REQUEST: remove vulkan drivers?

### ISSUE THREAD

**Issue by puccaso** [jmcerrejon/PiKISS#20]
is there anyway to add a undo/remove vulkan drivers/roll back feature?
it works great in windows, but when full screen, the screen tears and becomes jumbled really badly.

**Comment by jmcerrejon** [comment]
Sorry. Not possible atm. 😅

**Comment by Roburetto** [comment]
Vulkan seems to be working in fullscreen with PPSSPP here.

A question: is there a problem if we delete the leftover /pi/mesa_vulkan folder AFTER the driver is installed?

**Comment by jmcerrejon** [comment]
Delete it if it's your desire and if something goes wrong, install it again with PiKISS 😉

**Comment by puccaso** [comment]
i was able to fix the tearing by changing the graphics from Fake KMS to the Full KMS by adding the -pi4 to the overlay..
all good now 👍 
thank you guys!
