### ISSUE TITLE
GTA III and GTA: Vice City do not load in desktop

### ISSUE THREAD

**Issue by striderhiryux99** [jmcerrejon/PiKISS#200]
I installed PiKiss and attempted to add both GTA III and GTA: Vice City to the Games menu. I looked at the files_required text file to see if any additional files were needed. I found the re3 and reVC files (x86 Windows versions) and added them to the appropriate folders. I next attempted to play each of them on the PC for a few minutes until I could save. Upon quitting, I was able to finally obtain the sound.cache file (audio folders) for each as well. One issue that I am experiencing (on the Pi) is that once I click on those launchers in the desktop menu, a Wine window appears to load up several commands. About three seconds later, the screen flashes and leads back to the desktop, but it is at a lower resolution. Are there any steps I should take to make the games load correctly? Please let me know. Thank you.

**Comment by jmcerrejon** [comment]
A guy emailed me due to some GTA questions and he played with no hassle using RPi OS 11 32-Bit. I'll close this issue due to the date and tell me anyway If you could play with those requirements. Thank you"
