### ISSUE TITLE
aborting on install??? pi5 bookworm

### ISSUE THREAD

**Issue by NossieUK** [jmcerrejon/PiKISS#204]
errrr any thoughts@?

`curl -sSL https://git.io/JfAPE | bash`

`Aborting...
pi@Europa:~ $   `

**Comment by theofficialgman** [comment]
see https://github.com/jmcerrejon/PiKISS/issues/201

due to continual upstream changes, pi-apps has now implemented an installer natively so that the error you reported can never happen again https://github.com/Botspot/pi-apps/commit/e0aa01cc89459930830c9f06eb72c8d012262d0b

**Comment by jmcerrejon** [comment]
### My setup

Board: Raspberry Pi 5 8Gb
OS: Raspberry Pi OS Booksworm updated 64-bit

It works on my side.

![Screenshot 2024-01-02 at 18 37 29](https://github.com/jmcerrejon/PiKISS/assets/1942431/86d5aae4-e6b2-472b-8cfd-defc95d9f76b)

Send more info or try it again.
