### ISSUE TITLE
Packaged version of scrcpy incompatible with Android 14

### ISSUE THREAD

**Issue by bmwelby** [jmcerrejon/PiKISS#208]
Support for Android 14 [requires scrcpy 2.1.1 or higher](https://github.com/Genymobile/scrcpy/issues/70#issuecomment-1787882510). 

Current version packaged with PiKISS is 2.0. 

[Current version of scrcpy is 2.4](https://github.com/Genymobile/scrcpy).

**Comment by jmcerrejon** [comment]
> 
> Current version packaged with PiKISS is 2.0.
> 


I've compiled for aarch64 (64-bit). Tell me If you need armhf, too.
