### ISSUE TITLE
mGBA fails to load on Bookworm (RPi5)

### ISSUE THREAD

**Issue by zerothawg** [jmcerrejon/PiKISS#213]
Trying to run mGBA after PiKiss installation gives the error:
`./mgba-qt: error while loading shared libraries: libmgba.so.0.11: cannot open shared object file: No such file or directory`

**Comment by jmcerrejon** [comment]
Sorry. Bad linked libraries. Reinstall again.

Fixed at 62d6ee4edc44ea992e179fbea47a75988f913322

Thanks for the feedback! 😉
