### ISSUE TITLE
DELETED MY HOME FOLDER DURING UNINSTALL

### ISSUE THREAD

**Issue by mobilegmYT** [jmcerrejon/PiKISS#22]
I have nothing to say. 
![image](https://user-images.githubusercontent.com/44128563/91362083-e3cabc00-e7b6-11ea-874f-33db5a3efb6f.png)
All files in pi were deleted and maybe other places were affected?

**Comment by jmcerrejon** [comment]
Apologies. from where have you run PiKISS?. Menu icon, created Desktop icon, /home/pi/piKiss/piKiss.sh, cd /home/pi/piKiss && ./piKiss.sh

**Comment by jmcerrejon** [comment]
I tried all possible stages and the only way to get this was to invoke the script from a directory that was not _piKISS_, like:

```
pi@raspberrypi:~ $ /home/pi/piKiss/piKiss.sh
```

Next time, please use the shortcut icon or  ```cd piKiss && ./piKiss.sh ```

The only thing I can do is put a warning and indicate the directory to be deleted before It proceed.

Fixed on https://github.com/jmcerrejon/PiKISS/commit/1c91582f344a7ab2b4053690f100f8c15b79ed5b.
