### ISSUE TITLE
Request: Any chance of Half-Life 2 being added? 

### ISSUE THREAD

**Issue by CraigsBar** [jmcerrejon/PiKISS#226]
This has been proven to work on Raspberry Pi 5 when running Ubuntu OS, Would it be possible to incorporate it here for easy installations on devices running Raspberry Pi OS.

**Comment by jmcerrejon** [comment]
O tried with no success. Could you provide me any link with resources about it?

**Comment by actraiser30** [comment]
Help on the way

https://www.jamesfmackenzie.com/howto/how-to-install-half-life-2-halflife-2-on-raspberry-pi/

**Comment by CraigsBar** [comment]
I got it to compile on Raspberry Pi OS. But the graphics and character set are screwed up. 
![Uploading 1733912154577472005588806201914.jpg…]()
![Uploading 17339121837905707947718365227817.jpg…]()

**Comment by actraiser30** [comment]
Try this in config.txt

Change the dtoverlay=vc4-kms-v3d 

To dtoverlay=vc4-fkms-v3d

And the opposite

**Comment by CraigsBar** [comment]
Unfortunately that made no difference to the corrupted graphics/text.
![IMG20241211101335](https://github.com/user-attachments/assets/6a01e55b-ad07-40ed-8234-355510ae4793)
![IMG20241211101331](https://github.com/user-attachments/assets/c5c4aa9b-5cd2-42fa-914a-c1c989e9f65c)

**Comment by actraiser30** [comment]
Try that,if you compile it in 64 bit OS  do it in 32bit OS or the opposite again.

**Comment by jmcerrejon** [comment]
I already tried it (you can check [this](https://www.patreon.com/posts/108160432?utm_campaign=postshare_creator) open post at my Patreon. 

My issue was I only got 10-15 fps, and glitches in graphics as you commented.

For sure is some library used on RPi OS that is working on Ubuntu (Maybe the cause that guy compiled it there)

**Comment by CraigsBar** [comment]
Interestingly I created an ubuntu install on an SD card this morning and compiled it there (my Pi's both normally boot from NVMe SSD's) and I get the same issues. Tonight I will try to get it to compile on my OpenSuSE laptop (Lenovo Thinkpad T460 so nothing special) and see how that goes. I wonder if it is a wider issue with the source on github and recent Linux environments.

**Comment by CraigsBar** [comment]
I find valve proton is more game compatible than native wine, and
unfortunately that crashes at startup.

**Comment by actraiser30** [comment]
What about testing counterstrike source?

**Comment by actraiser30** [comment]
Tested various games with wine on Pi4 even painkiller was playable if you lower the graphics
Nosferatu was very slow thought.

**Comment by actraiser30** [comment]
What about this?

https://m.youtube.com/watch?v=xp-W1Axn8TM

**Comment by jmcerrejon** [comment]
I think it’d be great to focus on running native apps on PiKISS without relying on Wine or Proton for games. That way, we can keep things simple and straightforward! 😉

**Comment by actraiser30** [comment]
Native ports are better, yes,what about assault cube game can be build/work??

**Comment by CraigsBar** [comment]
![IMG20241211190551](https://github.com/user-attachments/assets/b8007cd9-7dc3-4600-9153-8adbdc161cc9)
So it's the same on OpenSuSE on intel x64 (core i5)

**Comment by Lohann** [comment]
Hi, I believe the Graphics issues is due an update in the Half-life from Steam, which is not supported by the current version of the source-engine:
https://github.com/nillerusr/source-engine/issues/397

Must test using a version prior to November 16 2024 release.

**Comment by Lohann** [comment]
Is possible to download an older version from Steam from here:
https://steamdb.info/depot/224/manifests/

Using this tool:
https://github.com/SteamRE/DepotDownloader

**Comment by Lohann** [comment]
Finally, I manage to get half-life 2 working natively on my **Rapsberry PI 5** with **Ubuntu 24.04**:
```bash
# Install dependencies
sudo apt-get install -y \
    unzip \
    wget \
    git-all \
    build-essential \
    pkg-config \
    ccache \
    libsdl2-dev \
    libfontconfig1-dev \
    libopenal-dev \
    libjpeg-dev \
    libpng-dev \
    libcurl4-gnutls-dev \
    libbz2-dev \
    libedit-dev


# Clone source-engine
cd ~/Downloads
git clone https://github.com/nillerusr/source-engine.git --recursive
cd source-engine

# Build Source-Engine, takes about ~22min to build on my RPi 5
python3 ./waf configure -T release --prefix=hl2 --build-games=hl2 --disable-warns
python3 ./waf build -p -v 
python3 ./waf install

# Download Half-Life 2, only the release from 17 November 2023 works:
# https://steamdb.info/patchnotes/12694556/
# Obs: Requires an steam account with the game.
cd ~/Downloads
wget https://github.com/SteamRE/DepotDownloader/releases/download/DepotDownloader_2.7.4/DepotDownloader-linux-arm64.zip
unzip DepotDownloader-linux-arm64.zip
./DepotDownloader -app 220 -depot 221 -manifest 3666218991449795038 -username <steam_username>

# Copy files to steam directory
rsync -ah --progress ./depots/221/16557524/hl2/* ~/Downloads/source-engine/hl2/hl2
cp ./depots/221/16557524/platform ~/Downloads/source-engine/hl2/

# start the game
cd ~/Downloads/source-engine/hl2
./hl2_launcher
```

**Comment by jmcerrejon** [comment]
Thank you so much, @Lohann!

After encountering some issues with the commands I was using, your guide was incredibly helpful. I have successfully compiled the engine and obtained the correct game data files on Raspberry Pi OS 64-bit.

![IMG_2221 2](https://github.com/user-attachments/assets/a84b69de-579c-4aeb-9074-721de15f1a2b)

Now, I need to put those commands into a user-friendly format for PiKISS users. I hope to accomplish this soon.

Thanks again!

**Comment by jmcerrejon** [comment]
Added f0e37f52f03584c1006f2ac72f07a77397f17402
