### ISSUE TITLE
Other package managers

### ISSUE THREAD

**Issue by afritsch89** [jmcerrejon/PiKISS#23]
As support for more OSs opens up we are already starting to see more than apt on the scene.

I recommend using a catch to see what package manager they use.

I fixed my instance with  find replace in the scripts, but you know, moving forward.

**Comment by jmcerrejon** [comment]
As you can see in the latest scripts I made, I'm try to isolate commons OS funcions to catch in the future for the purpose you mentioned. Thanks for the feedback!.
