### ISSUE TITLE
Emulators doesn't seems to work

### ISSUE THREAD

**Issue by asfo** [jmcerrejon/PiKISS#3]
Hope you can see my issue :)

I tried to install PiKISS but doesn't seems to work on Raspberry Pi Zero (W)...

I did the git clone, and executed the .sh file so everything went fine there, but after I install the GBA Emulator (Or SNES, I just tried those) shows an error that the "helper.sh" can't be found...

After that shows that the emulator "is installed correctly" but when I press "Y" to start the default game/free game or something like that to test it, it does nothing because an error (I don't have my RBPZ right now to show you but if you give me an answer here I will upload an screenshot)

**Comment by jmcerrejon** [comment]
Didn't have a Raspberry Pi Zero to test. I'll try to test with RPi 3 Model B+ (2017)

**Comment by jmcerrejon** [comment]
Don't have a Raspberry Pi Zero to test. I'll try to test with RPi 3 Model B+ (2017)

**Comment by actraiser30** [comment]
Hello,can you make a script to be able to install PiKiss to the Retropie ??

or it is possible like this if yes how?

thanks

**Comment by jmcerrejon** [comment]
> Hello,can you make a script to be able to install PiKiss to the Retropie ??
> 
> or it is possible like this if yes how?
> 

_Retropie_ is a _Debian_ distro, so login into the OS through _SSH_ and clone this repo. Piece of cake! 😊

**Comment by actraiser30** [comment]
thanks what i mean is to make a script for the retropie setup menu to install it from there like installing a port for example

**Comment by actraiser30** [comment]
Also can you put in the server menu the software Transmission torrent server?

something else,the ramlog page does not exist anymore so you cannot install it, even if you could install it is way outdated and as reported by many people not working correctly,you can replace it with the log2ram though:

https://github.com/azlux/log2ram

**Comment by jmcerrejon** [comment]
> thanks what i mean is to make a script for the retropie setup menu to install it from there like installing a port for example

Oh, I know your thoughts. Never build a script for RetroPie. I note it down in my TODO list with a 
 script to install a torrent server. 

> Also can you put in the server menu the software Transmission torrent server?
> 
> something else,the ramlog page does not exist anymore so you cannot install it, even if you could install it is way outdated and as reported by many people not working correctly,you can replace it with the log2ram though:
> 
> https://github.com/azlux/log2ram

Thks for the help with ramlog. Didn't know that.

**Comment by actraiser30** [comment]
if you can put Transmission torrent server in servers will be great thanks

**Comment by actraiser30** [comment]
Hello, in dune legacy the mouse does not work only the keyboard works is there a setting or workaround to correct this?

**Comment by jmcerrejon** [comment]
Let me check it out this weekend.

**Comment by jmcerrejon** [comment]
I use to support the latest Raspbian version. The game is playable and it works flawlessly on Raspbian Buster.

I guest your problem is with SDL2 lib on Stretch. Try another SDL2 game from Debian repositories. You have another script to install manually SDL2, follow the script step by step. My recommendation is that upgrade your Raspbian  to Buster 😄

Good luck!

**Comment by actraiser30** [comment]
i tried it in both buster and stretch in buster it was working but the mouse pointer is not visible do you know how to fix this?

**Comment by jmcerrejon** [comment]
like I said, your issue is with SDL2, I just tested with the latest Raspbian and all is working.

**Comment by actraiser30** [comment]
how did you install sdl exactly?

**Comment by jmcerrejon** [comment]
It’s already installed

**Comment by actraiser30** [comment]
dune legacy does not install sdl2 if i run the game like this i get an sdl error

**Comment by actraiser30** [comment]
anyway thanks i will figure this later for now it will be great to add the transmission torrent server and the plex media server.

and more games in the future if you need help let me know
