### ISSUE TITLE
REQUEST: Heroes of might and magic 3: Complete

### ISSUE THREAD

**Issue by Ch11kk1** [jmcerrejon/PiKISS#31]
Hi,

It would be really awesome to get HOMM 3 complete to work on RPI 4...

**Comment by jmcerrejon** [comment]
Please, petition request through Discord or Patreon channel. I want to keep issues for its purpose 😉

**Comment by Ch11kk1** [comment]
Okay, my bad. I'm quite new to RPi 4 and Github so next time I use right channel to give my requests :) Though, I think that it's an issue the HOMM 3 isn't working yet :rofl:
