### ISSUE TITLE
Old, unoptimized version of xash FWGS is used

### ISSUE THREAD

**Issue by Solexid** [jmcerrejon/PiKISS#33]
https://github.com/jmcerrejon/PiKISS/blob/master/scripts/games/half.life.sh Its not OPTIMIZED for raspberry4, its armv6 build of engine, not aarch64 or armv7. Remove Optimized string or update.

**Comment by Solexid** [comment]
>>· Based on engine at 
And link for SDK of game library, not engine, engine is XASH.

**Comment by jmcerrejon** [comment]
Duplicated https://github.com/jmcerrejon/PiKISS/issues/32
