### ISSUE TITLE
Half-Life won't install properly

### ISSUE THREAD

**Issue by phil-ide** [jmcerrejon/PiKISS#34]
7Zip reports 1 file, 0 bytes. When I try to run the game, it complains it cannot find the folder 'valve'.

RPI4 running Raspberry Pi OS

**Comment by jmcerrejon** [comment]
Yes. Trying to improve the code when data files can't be downloaded. In the meantime, the engine is installed and you only need to copy valve directory into ~/games/half-life.

Enjoy! 😄
