### ISSUE TITLE
Option to install alacritty doesn't do anything

### ISSUE THREAD

**Issue by notevenodd** [jmcerrejon/PiKISS#35]
It looks like main menu is looking for a scripts/others/alacritty.sh and then cannot find it.
Would be great to have easy alacritty install from the Pi.

**Comment by jmcerrejon** [comment]
Ups. This is a feature, not a bug 😂 Jokes aside, I was working on that until all the stuff about datas files came to me. I'll try to add it soon. 😉

**Comment by jmcerrejon** [comment]
Closed with 957ea1639f35045c10d503fa8cda940b4545b4d0
