### ISSUE TITLE
Half-Life fresh install issues

### ISSUE THREAD

**Issue by rhester72** [jmcerrejon/PiKISS#36]
1) client_armv6hf.so is not placed in valve/cl_dlls and thus cannot be found at startup (a workaround that seems like it would work regardless of whether the user has a pre-cached copy of the game content would be to create ~/games/half-life/cl_dlls and place it there, it seems to work just as well)

2) A pristine copy of the valve directory taken from a fresh Steam install does not result in a playable game - specifically, the menu items New Game and Training Room are ghosted and cannot be selected.

**Comment by jmcerrejon** [comment]
Fixed. Now the ./half-life.sh check if some missing files and add it to your valve directory.

**Comment by rhester72** [comment]
Perfect, thank you!
