### ISSUE TITLE
Unable to install Diablo

### ISSUE THREAD

**Issue by KonstiSG** [jmcerrejon/PiKISS#39]
I'm unable to install Diablo 1,
it seems like the script queries "url_to_shareware_links" instead of the actual URL.

Installing Diablo 1, please wait...

./scripts/helper.sh: Zeile 253: local: DATA_URL: Schreibgeschützte Variable.
./scripts/helper.sh: Zeile 220: local: DATA_URL: Schreibgeschützte Variable.
./scripts/helper.sh: Zeile 221: DATA_URL: Schreibgeschützte Variable.
./scripts/helper.sh: Zeile 257: DATA_URL: Schreibgeschützte Variable.

Do you want to play Diablo1 now? [y/n]

**Comment by jmcerrejon** [comment]
83348850cb9f6129a17c18fa6b167840f9b981dc fix the issue
