### ISSUE TITLE
Can't install Half Life on my pi 4

### ISSUE THREAD

**Issue by joaco05** [jmcerrejon/PiKISS#40]
After saying that i own a copi it says a text about searching and then it closes.

**Comment by jmcerrejon** [comment]
Read the [README](https://github.com/jmcerrejon/PiKISS/blob/master/README.md#-data-files--) file. You need the data files compressed on the cloud (this is going to change very soon) in a file inside *res/* directory called *magic-air-copy-pikiss.txt*

**Comment by joaco05** [comment]
I put it in the txt file like this 
![image](https://user-images.githubusercontent.com/55862776/96918667-07417880-1481-11eb-95f1-d057a28a3e36.png)
and still don't work.

There is a form to do it manually?
