### ISSUE TITLE
Quake2 installation: unrecognized file compression

### ISSUE THREAD

**Issue by ChieftainY2k** [jmcerrejon/PiKISS#43]
Hardware: RPI4 2GB
OS: Raspbian 10 (buster)

Steps to reproduce:
1) Install PiKISS
2) Attempt to install Quake2

![image](https://user-images.githubusercontent.com/968529/97549994-5cc1dc00-19d1-11eb-9758-09f98e151846.png)

Which results in:

![image](https://user-images.githubusercontent.com/968529/97550174-9e528700-19d1-11eb-873b-6d499ce7a823.png)

**Comment by jmcerrejon** [comment]
Fixed 9ea46301503d6535dbaa3468494fa31abfe91a35
