### ISSUE TITLE
Suggestion: move all software to docker containers for better isolation and maintenance

### ISSUE THREAD

**Issue by ChieftainY2k** [jmcerrejon/PiKISS#44]
Just a thought: would it be feasible to move some of the apps managed by PiKISS to docker images and thus run them in containers ? 
Such approach would require:
- Create images for each app
- Create manifest files to execute containers with proper runtime configuration (volumes, privileges etc.) 

Benefits:
- Easy installation/uninstallation/maintenance without installing any host libraries and dependencies.
- Clean approach
- Each piece of software could be maintained separately.
- Low or close to none docker isolation overhead on CPU/resources

What do you think ?

**Comment by jmcerrejon** [comment]
I don't know if users might want install Docker for just some apps. Don't get me wrong, I like the idea, but containers is a philosophy that not all users understand. Maybe in a future, I can consider it. Thank you for the suggestion.
