### ISSUE TITLE
Ability to Uninstall Box86

### ISSUE THREAD

**Issue by Alextrapixel** [jmcerrejon/PiKISS#46]
I've installed Box86 over PiKiss. But when I need to uninstall it, I found there is only update option. Is there an option to uninstall Box86?

**Comment by jmcerrejon** [comment]
Ok. In the meantime...

```sh
rm -rf /usr/local/bin/box86 /etc/binfmt.d/box86.conf /usr/lib/i386-linux-gnu/libstdc++.so.6 /usr/lib/i386-linux-gnu/libstdc++.so.5 /usr/lib/i386-linux-gnu/libgcc_s.so.1
```

**Comment by jmcerrejon** [comment]
Enhanced! https://github.com/jmcerrejon/PiKISS/commit/bffb883ddb32670d09b50d1d6b16052d0264c237

**Comment by Alextrapixel** [comment]
awesome... thanks!
