### ISSUE TITLE
Suggestion : wine

### ISSUE THREAD

**Issue by jakues** [jmcerrejon/PiKISS#48]
this will great if pikiss can provide wine install. thanks

**Comment by jmcerrejon** [comment]
Thanks for the suggestion. Wine is easily installable through the repository.

**Comment by jakues** [comment]
so, need instal box86 ?

**Comment by jmcerrejon** [comment]
I don't know what you want exactly. Twister OS has a custom wine. On Raspberry Pi OS just `sudo apt install wine`.
