### ISSUE TITLE
How to use this with other OS?

### ISSUE THREAD

**Issue by memidhun** [jmcerrejon/PiKISS#55]
I am using Kali Linux in raspberry pi ..The pi kiss was successfully installed and it worked in terminal. I tried installing scrcpy using this .The program file was downloaded and installed but it's not opening whenever i run ./scrcpy it shows me "scrcpy no such file or directory" .I moved the entire folder to root folder but still it gave me the same error. I tried running it using the icon in the application menu but  it did't worked either.Is this somewhat related to the path because in kali linux home directory is in- /home/kali 
where as in rasbian-  /home/pi.

**Comment by jmcerrejon** [comment]
Check the README file. PiKISS is only supported on Raspberry Pi OS 32 bits. Maybe it was installed, so search inside your partition where it is. Study the script for some tips and... good luck! 😊

**Comment by memidhun** [comment]
> Check the README file. PiKISS is only supported on Raspberry Pi OS 32 bits. Maybe it was installed, so search inside your partition where it is. Study the script for some tips and... good luck!

So it won't run on 64 bit ? How can i read the script?

**Comment by jmcerrejon** [comment]
It doesn't support 64 bits atm. All the scripts are inside ~/piKiss/scripts

**Comment by memidhun** [comment]
> It doesn't support 64 bits atm. All the scripts are inside ~/piKiss/scripts

oh is there any way i can use scrcpy in kali linux on pi? Its urgen! 
Thanks for helping me

**Comment by jmcerrejon** [comment]
Sorry. I can't help you. I don't know anything about Kali. Good luck!
