### ISSUE TITLE
How about Diablo Hellfire

### ISSUE THREAD

**Issue by gandalf17** [jmcerrejon/PiKISS#57]
Diablo ends abruptly. And there is no levels in game. Could you please add hellfire

**Comment by jmcerrejon** [comment]
What do you mean ends abruptly?

Please, more info if you need help: OS, I guess 32 bits env.,..

I'm not the author of the port, just tell him to give support to Hellfire.

**Comment by gandalf17** [comment]
Thanks for the super fast response. When you kill diablo you can start a new game but the game is super easy and you have no proof that you killed diablo. Game doesn't let you save after you kill diablo. Technically you start before diablo kill every time.

**Comment by jmcerrejon** [comment]
Here you have the port: https://github.com/diasurgical/devilutionX/

Good luck!
