### ISSUE TITLE
Half-life failing to load

### ISSUE THREAD

**Issue by rubyoptics** [jmcerrejon/PiKISS#59]
Half-life fails to initialise - Xash Error - W_LoadWadFile: couldn't load gfx.wad.  Valve file is in directory.

**Comment by jmcerrejon** [comment]
Working here with the latest _Raspberry Pi OS 32 bits_.

Make sure you run the game through the menu or using _./half-life.sh_.

Tested with Half Life from _Steam_.

Check the official repo if you have issues: https://github.com/FWGS/xash3d

Here is the list of files I have: [half-life-files.txt](https://github.com/jmcerrejon/PiKISS/files/5761404/half-life-files.txt)

Good luck!
