### ISSUE TITLE
Remove /home/pi/ in favor of %HOME%/ or ~/

### ISSUE THREAD

**Issue by RandamuMaki** [jmcerrejon/PiKISS#62]
Please remove the /home/pi/ links in favor of XDG-standards so your scripts will use on Raspberry Pi machines who have removed the Pi account for security purposes or other.
Hard links should only be used for things like /usr/ and not /home/%USER%/ because %USER% may change per system.

**Comment by jmcerrejon** [comment]
Maybe you see it in older scripts I couldn't review. I’ll check it out in a few days. Happy new 🎊

**Comment by Pi-Mania** [comment]
This will fix a lot of issues i had using FenixOS also. (As there is no \home\pi user/folder) Older scripts i think. newer ones seem to work fine.

**Comment by jmcerrejon** [comment]
I'm on it, but as I said in the README, PiKISS is only supported on RPi OS 32 bits, so use it at your own risk.

**Comment by jmcerrejon** [comment]
Done!

**Comment by fenixlinuxos** [comment]
Thank you Jose. I was modifying pikiss and blocking the updates now it's not necessary.

**Comment by fenixlinuxos** [comment]
Thank you Jose. I was modifying pikiss and blocking the updates, now it's not necessary.
