### ISSUE TITLE
Cant run ZOOM.

### ISSUE THREAD

**Issue by curyjorge98** [jmcerrejon/PiKISS#63]
Im trying to run Zoom on my Raspberry PI OS (updated/upgraded).

My Username is not "pi" and I get this error on installing script for Box86:

 Extracting...
[sudo] senha para vieira: 
/bin/sh: 1: cd: can't cd to /home/pi/box86/build
make[2]: *** [CMakeFiles/WRAPPERS.dir/build.make:287: CMakeFiles/WRAPPERS.dir/depend] Error 2
make[1]: *** [CMakeFiles/Makefile2:369: CMakeFiles/WRAPPERS.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

Box86 has been installed.

Downloading...

zoom_i686.tar.xz    100%[===================>]  37,95M  1,76MB/s    em 34s     

Extracting...

Making a cool script called zoom-rpi.sh...

Generating icon...

Done!. Type /home/vieira/apps/zoom/zoom-rpi.sh or Go to Menu > Internet > Zoom.

Press [ENTER] to run...

Box86 missing, please install

Press [Enter] to go back to the menu...

Thanks,

Happy New Year.

**Comment by jmcerrejon** [comment]
Weird. It should be working because I always use $HOME (it should be /home/vieira). If box86 is the problem, you can install it through Emulators > Box86.

I close the issue but open this again if you get another issue.
