### ISSUE TITLE
OpenMW not downloading as Readonly missing from Script File

### ISSUE THREAD

**Issue by Pi-Mania** [jmcerrejon/PiKISS#68]
readonly missing from beginning of BINARY_URL line so Openmw fails to start downloading. 😁

**Comment by jmcerrejon** [comment]
BINARY_URL can't be read only because is overwrite if you have the full version. Make sure the file is online on your res/magic-air-copy-pikiss.txt

**Comment by Pi-Mania** [comment]
Its the openmw files that fail to download and on Twister also. My morrowind files copy to games folder just fine.  Maybe i explain badly, test and you will see what i mean. Thanks

**Comment by jmcerrejon** [comment]
I run the script, then I press n to the Magic Air Copy message, and then start to download the binary files. Anyway, read the BINARY_URL and copy the URL, then paste it in the browser (or wget it). The file is online right now.
