### ISSUE TITLE
Serious Sam Install

### ISSUE THREAD

**Issue by Pi-Mania** [jmcerrejon/PiKISS#73]
Asks if i have data files. If i say YES it just copies/extracts that archive to pi/user/games and exits/errors out. (achive is from COG version and extracts and works if i do install manually btw)  If i say NO it then downloads the compiled libraries needed (ssam-bin-1.05-rpi4) into pi/games/ssam Shortcuts created do not seem to point to correct location.

if i extract my data files and place your compiled binaries in the /Bin folder then start with ,/ssam  it does work however.  

(BIG TIP for those having the game exits after load issue: hit escape after first loading to get into game start game menu, then first go into a single player/technology Test, then end that game. Now it will work fine (until you exit)  upto 720p on Pi 4@@2Ghz)

Hope this helps

Thanks for all you do, its a GREAT project!

**Comment by jmcerrejon** [comment]
I've refactored the code. Closed with https://github.com/jmcerrejon/PiKISS/commit/7d647e245269b52ea575f7fc21b6685d7f8c160d
