### ISSUE TITLE
AVP no sound

### ISSUE THREAD

**Issue by retro24** [jmcerrejon/PiKISS#74]
Hello, i have installed avp from your script in my RPI 4 it runs fine but i dont have sound in the game?

any suggestion on whats wrong ??

**Comment by retro24** [comment]
In Raspberry pi 3 the sound works in Raspberry pi 4 does not work,so you must have build the executable in an Rpi3 or not?

**Comment by retro24** [comment]
update

installed pulseaudio and enable it now i have sound in the game from the headphones only need to figure out how to get it to the speakers

**Comment by jmcerrejon** [comment]
So the problem is on your side. I’ll close the issue. Good luck!

**Comment by symbios24** [comment]
Its not in my side the problem is general i suggest you try and see for your self and fix it, if you can,its a general rpi4 problem

**Comment by jmcerrejon** [comment]
Ok. I’ll try it and tell you.

**Comment by jmcerrejon** [comment]
Tested. It works. Sound effects are the only ones that work (I never tested the music). Good luck!
