### ISSUE TITLE
Pi400, Super Mario

### ISSUE THREAD

**Issue by micv2** [jmcerrejon/PiKISS#76]
Hello, Super Mario does not start after installation (Vertex Shader compilation failed). (Pi400, Twister, PiKiss). 

![Mario](https://user-images.githubusercontent.com/45406373/104048092-01874380-51e3-11eb-86c6-3f87696ebee6.JPG)

What am I doing wrong? Best regards, MiC

**Comment by jmcerrejon** [comment]
It's an issue with libraries that is causing issues on Twister OS. Check [this link](https://discord.com/channels/670543161525010442/700827460454973522/795969209460981760).
