### ISSUE TITLE
AVP - Pi400

### ISSUE THREAD

**Issue by DisasterIncarnate** [jmcerrejon/PiKISS#77]
Script runs, installs fine, avp launches, however when i am presented with the profile selection, i hit enter on my profile and the game drops to terminal with "Segmentation Fault".

**Comment by jmcerrejon** [comment]
I'm not an owner of the Pi400, so I can't test it. It works on Pi4 and should work on the latest Pi model. I'll try to search for someone with the Pi400 who wants to test the script.

**Comment by DisasterIncarnate** [comment]
probably should have mentioned this is on TwisterOS as well.

**Comment by jmcerrejon** [comment]
https://github.com/jmcerrejon/PiKISS/issues/72
