### ISSUE TITLE
Suggestion: Add option to (re)install raspi-config

### ISSUE THREAD

**Issue by Develaupair** [jmcerrejon/PiKISS#79]
`raspi-config` is a pretty essential tool which theoretically works with all debian-based operating systems on the pi, at least from my understanding. Therefore, it would be cool to have a option to batch install (or reinstall) the tool and it's dependencies.

**Comment by jmcerrejon** [comment]
I think raspi-config is not difficult to install, and it's not a tool you would uninstall from your system. Thks anyway for the suggest ☺️
