### ISSUE TITLE
PiKiss Uninstall

### ISSUE THREAD

**Issue by slashtechno** [jmcerrejon/PiKISS#80]
I was wondering if it is possible to make it so when PiKISS is uninstalled is uninstalls all apps that were installed through PiKISS?

Also is it possible to make PiKISS interface with [Pi-Apps](https://github.com/Botspot/pi-apps)

**Comment by jmcerrejon** [comment]
I'm afraid I don't have a log about all software PiKISS install on your OS. 

I like terminal, but I'm considering make a GUI for desktop. Thanks for the suggestions. Enjoy PiKISS!
