### ISSUE TITLE
Suggestions: Server and Clients for gemini protocol

### ISSUE THREAD

**Issue by pasdechance** [jmcerrejon/PiKISS#81]
The gemini fanbase is growing, would it be possible to add links for a gemini server and client? Agate (server) runs fine on any pi and Amfora/(client) too.

https://github.com/mbrubeck/agate

https://github.com/makeworld-the-better-one/amfora

**Comment by jmcerrejon** [comment]
I don't know what it is, but I'll add it to my TODO list. Thks!
