### ISSUE TITLE
Zoom client Google login fails 

### ISSUE THREAD

**Issue by freevan** [jmcerrejon/PiKISS#87]
I am registered to Zoom with my Google  account. When I choose sign in with Google option, Chromium browser starts with a new tab and nothing else happens.

**Comment by jmcerrejon** [comment]
Take into account Zoom is "emulated" with box86. If the app tries to run another app, probably doesn't work as expected. So there is nothing I can do 😩

**Comment by Itai-Nelken** [comment]
I think the problem is xdg-open cant open zoom.
nothing that can be fixed easily 😔

**Comment by jmcerrejon** [comment]
Yeah, I think box86 is like a sandbox and is difficult to “connect” the apps each other.
