### ISSUE TITLE
Request : Turbo Rascal Syntax error, “;” expected but “BEGIN”

### ISSUE THREAD

**Issue by mbodomi** [jmcerrejon/PiKISS#89]
Hi! Turbo Rascal Syntax error, “;” expected but “BEGIN” is a gamedev/demoscene devtool for 6502-based and other systems.
It needs qt6

can be found here:
https://github.com/leuat/TRSE/

**Comment by jmcerrejon** [comment]
When I added that program on PiKISS? 🤔
I think you are in the wrong place 🤷‍♂️
