### ISSUE TITLE
Add dependencie python3-pip

### ISSUE THREAD

**Issue by sergiohf** [jmcerrejon/PiKISS#97]
I was trying to install vulkan in my rpi4 and the script always finish with an error. After look at the error i saw it was missing the installation of  python3-pip, with prevents using pip3 in the script, so I suggest that this package is added to the dependencies of the Vulkan script. Tks

**Comment by jmcerrejon** [comment]
That pkg is installed by default on Raspberry Pi OS.

Anyway, You are the second person who tell me something about it, so consider it done. 😉

**Comment by sergiohf** [comment]
Tks, i use Raspian Lite, and this package is not installed.
