### ISSUE TITLE
scrcpy 1.17 incomplete installation

### ISSUE THREAD

**Issue by brightentayle** [jmcerrejon/PiKISS#98]
Installing scrcpy 1.17 with PiKISS results in a broken install, since the scrcpy-server executable is missing completely, despite the fact it's essential for the program to run and the 1.13 server isn't supported by the new version.

It doesn't seem like scrcpy-server is part of the tarball PiKISS downloads, either.

**Comment by jmcerrejon** [comment]
Fixed 8cd5284f1e07bb6b9503cd575de87ec6818c6535
