### ISSUE TITLE
NBlood also installs Rednukem and PCExhumed, not mentioned anywhere in the installer

### ISSUE THREAD

**Issue by brightentayle** [jmcerrejon/PiKISS#99]
The option to install Blood also throws ports for Redneck Rampage and Exhumed/Powerslave into the same exact folder. This... fine bonus isn't mentioned anywhere in the installer, and there's no option to install either of those Build Engine-based ports separately. Perhaps it's time to expand Blood into a larger BuildEngine script?

**Comment by jmcerrejon** [comment]
My idea is to add those engine in the future. That's the reason because the script is installing those engines. So no problems here. It's all Ok.

**Comment by brightentayle** [comment]
Good to hear, thanks!
